####################################################
# DVrouter.py
# Name:
# HUID:
#####################################################

from router import Router

import json

from packet import Packet

infinite = 100

class DVrouter(Router):
    """Distance vector routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        # TODO
        # add your own class fields and initialization code here
        self.distance_vector = {}
        self.forwarding_table = {}
        self.distance_vector[ord(self.addr)] = 0
        self.forwarding_table[ord(self.addr)] = None
        self.neighbors = {}
        self.neighbor_port = {}
        self.direct_link_cost = {}

        # Checks for removal of links with special node (-1)
        # 1 for addition package, -1 for removal package, 0 for normal operation
        self.distance_vector[-1] = 0
        self.forwarding_table[-1] = None

        self.src_debug_addr = '-2'
        self.dst_debug_addr = '-2'

        #debug_str = f"DVrouter(addr={self.addr}, links={self.links}, distance_vector={self.distance_vector}, forwarding_table={self.forwarding_table})"
        #print(debug_str)

    def handle_packet(self, port, packet):
        """Process incoming packet."""
        # TODO
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)

            if(ord(packet.dst_addr) in self.forwarding_table):
                self.send(self.forwarding_table[ord(packet.dst_addr)], packet)

        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the received distance vector is different
            #   update the local copy of the distance vector
            #   update the distance vector of this router
            #   update the forwarding table
            #   broadcast the distance vector of this router to neighbors

            #print(f"Received routing packet from {packet.src_addr} at router {self.addr}")
            
            if(not hasattr(packet, "content") or packet.content is None):
                #print(f"Error: Routing packet from {packet.src_addr} does not contain distance vector data.")
                return

            new_distance_vector = json.loads(packet.content)

            #print(f"Received distance vector from neighbor {packet.src_addr} at router {self.addr}: {new_distance_vector}")

            src_neighbor = ord(packet.src_addr)

            new_distance_updated = False

            if(src_neighbor not in self.neighbors):
                self.neighbors[src_neighbor] = new_distance_vector
                new_distance_updated = True
            else:
                for key, value in new_distance_vector.items():
                    if(key == '-1'):
                        continue

                    if(key not in self.neighbors[src_neighbor] or self.neighbors[src_neighbor][key] != value):
                        self.neighbors[src_neighbor][key] = value
                        new_distance_updated = True

            #print(f"All neighbors of router {self.addr}: {self.neighbors}")

            if(not new_distance_updated):
                #print(f"No new distance information from neighbor {packet.src_addr} at router {self.addr}.")
                return
            
            new_distance_updated = False

            if(self.addr == self.src_debug_addr):
                if(ord(self.dst_debug_addr) not in self.distance_vector):
                    print(f"Cost to {self.dst_debug_addr} is infinite")
                else:
                    print(f"Cost to {self.dst_debug_addr}: {self.distance_vector[ord(self.dst_debug_addr)]}")

            # If the package indicates a link removal, set the distance to all destinations through that neighbor to infinity
            if(new_distance_vector['-1'] == -1):
                for key in self.distance_vector:
                    if(key != ord(self.addr) and key != src_neighbor and key != -1):
                        if(self.forwarding_table.get(key) == port):
                            self.distance_vector[key] = infinite
                            self.forwarding_table[key] = None
                            new_distance_updated = True

            if(new_distance_vector['-1'] == 1 or new_distance_vector['-1'] == 0):
                for key, value in new_distance_vector.items():
                    ikey = int(key)
                    if(ikey == ord(self.addr) or ikey == src_neighbor or ikey == -1):
                        continue
                    if(ikey not in self.distance_vector):
                        #print(f"New destination {chr(ikey)} discovered from neighbor {packet.src_addr} at router {self.addr}")
                        self.distance_vector[ikey] = self.direct_link_cost.get(src_neighbor, infinite) + value
                        self.forwarding_table[ikey] = port
                        new_distance_updated = True

            for key in list(self.distance_vector.keys()):
                if key == ord(self.addr) or key == -1:
                    continue
                
                best_cost = infinite
                best_port = None
                
                for neighbor, neighbor_distance_vector in self.neighbors.items():
                    if str(key) not in neighbor_distance_vector:
                        continue
                    neighbor_reports = neighbor_distance_vector[str(key)]
                    if neighbor_reports >= infinite:
                        continue
                    new_cost = neighbor_reports + self.direct_link_cost.get(neighbor, infinite)
                    if new_cost < best_cost:
                        best_cost = new_cost
                        best_port = self.neighbor_port[neighbor]
                
                    # Also consider direct link to this node
                    if key in self.direct_link_cost and self.direct_link_cost[key] < best_cost:
                       best_cost = self.direct_link_cost[key]
                       best_port = self.neighbor_port.get(key)
                
                    if self.distance_vector[key] != best_cost:
                        self.distance_vector[key] = best_cost
                        self.forwarding_table[key] = best_port
                        new_distance_updated = True

            if(self.addr == self.src_debug_addr):
                printdistance_vector = {chr(key): value for key, value in self.distance_vector.items() if key != -1}
                printforwarding_table = {chr(key): value for key, value in self.forwarding_table.items() if key != -1}
                print(f"Updated distance vector at router {self.addr} after receiving update from neighbor {packet.src_addr}: {printdistance_vector}")
                print(f"Forwarding table at router {self.addr} after receiving update from neighbor {packet.src_addr}: {printforwarding_table}")

            self.distance_vector[-1] = new_distance_vector['-1']

            if(new_distance_updated):
                for out_port in self.links:
                    if(out_port != port):
                        packet = Packet(Packet.ROUTING, src_addr=self.addr, dst_addr=None)
                        packet.content = json.dumps(self.distance_vector)
                        self.send(out_port, packet)

            self.distance_vector[-1] = 0

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors

        #print(f"New link: {self.addr} <-> {endpoint} with cost {cost}")

        endpoint = ord(endpoint)
        self.neighbor_port[endpoint] = port
        self.direct_link_cost[endpoint] = cost

        newForwardingInfo = False
        
        if(self.addr == self.src_debug_addr):
            if(ord(self.dst_debug_addr) not in self.distance_vector):
                print(f"Cost to {self.dst_debug_addr} is infinite")
            else:
                print(f"Cost to {self.dst_debug_addr}: {self.distance_vector[ord(self.dst_debug_addr)]}")


        if(endpoint not in self.distance_vector):
            if(self.addr == self.src_debug_addr and chr(endpoint) == self.dst_debug_addr):
                print(f"New destination {chr(endpoint)} discovered from new link at router {self.addr}")
            self.distance_vector[endpoint] = cost
            self.forwarding_table[endpoint] = port
            newForwardingInfo = True

        if(self.distance_vector[endpoint] > cost):
            self.distance_vector[endpoint] = cost
            self.forwarding_table[endpoint] = port
            newForwardingInfo = True

        if(self.addr == self.src_debug_addr):
            printdistance_vector = {chr(key): value for key, value in self.distance_vector.items() if key != -1}
            printforwarding_table = {chr(key): value for key, value in self.forwarding_table.items() if key != -1}
            debug_str = f"Updated at router {self.addr} after new link: {printdistance_vector}, forwarding_table={printforwarding_table}"
            print(debug_str)



        # Set the special node to 1 to indicate a new link has been added
        self.distance_vector[-1] = 1

        if(newForwardingInfo):
            for out_port in self.links:
                #print(f"Broadcasting updated distance vector from {self.addr} to neighbor {port}")

                packet = Packet(Packet.ROUTING, src_addr=self.addr, dst_addr=None)
                packet.content = json.dumps(self.distance_vector)
                self.send(out_port, packet)

        self.distance_vector[-1] = 0

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors

        #print(f"Removing link: {self.addr} <-> {port}")

        lost_neighbor = next((key for key, value in self.neighbor_port.items() if value == port), None)
        if lost_neighbor is not None:
            del self.neighbor_port[lost_neighbor]
            del self.neighbors[lost_neighbor]
            del self.direct_link_cost[lost_neighbor]

        lost_keys = {key for key, value in self.forwarding_table.items() if value == port}
                
        for key in lost_keys:
            self.distance_vector[key] = infinite
            self.forwarding_table[key] = None

        for key in lost_keys:   
            for neighbor, neighbor_distance_vector in self.neighbors.items():
                if(self.distance_vector[neighbor] >= infinite):
                    continue
                if(str(key) not in neighbor_distance_vector):
                    continue

                new_cost = neighbor_distance_vector[str(key)] + self.direct_link_cost[neighbor]
                if(self.distance_vector[key] > new_cost):
                    self.distance_vector[key] = new_cost
                    self.forwarding_table[key] = self.neighbor_port[neighbor] 

        # Set the special node to -1 to indicate a link has been removed
        self.distance_vector[-1] = -1

        for out_port in self.links:
                packet = Packet(Packet.ROUTING, src_addr=self.addr, dst_addr=None)
                packet.content = json.dumps(self.distance_vector)
                self.send(out_port, packet)

        self.distance_vector[-1] = 0

    def handle_time(self, time_ms):
        """Handle current time."""

        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the distance vector of this router to neighbors

            self.distance_vector[-1] = 0

            for out_port in self.links:
                packet = Packet(Packet.ROUTING, src_addr=self.addr, dst_addr=None)
                packet.content = json.dumps(self.distance_vector)
                self.send(out_port, packet)

            self.distance_vector[-1] = 0

            pass

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded

        printdistance_vector = {chr(key): value for key, value in self.distance_vector.items() if key != -1}
        printforwarding_table = {chr(key): value for key, value in self.forwarding_table.items() if key != -1}

        debug_str = f"DVrouter(addr={self.addr}, distance_vector={printdistance_vector}, forwarding_table={printforwarding_table})"
        return debug_str
